global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
  
  - job_name: 'fluent-bit'
    static_configs:
      - targets: ['fluent-bit:2020']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'forgejo'
    static_configs:
      - targets: ['forgejo:3000']

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8180']
