---
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /var/lib/loki

  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  
  ring:
    kvstore:
      store: inmemory

  replication_factor: 1

query_range:
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 64
    compression: snappy

schema_config:
  configs:
    - from: 2023-01-01
      schema: v12
      store: tsdb
      object_store: filesystem
      index:
        prefix: index_
        period: 24h
