clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s

server:
  http_listen_port: 3000
  register_instrumentation: true

positions:
  filename: /var/log/positions.yaml

scrape_configs:
  - job_name: docker
    pipeline_stages:
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container_name
      - regex: __meta_docker_container_log_stream
        action: labelmap
        replacement: stream
      # TODO extract labels containing the service name
      # tip: https://grafana.com/docs/loki/latest/send-data/promtail/configuration/#docker_sd_config
