version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_TLS_CERTIFICATE: /cert/registry.pem
      REGISTRY_HTTP_TLS_KEY: /cert/registry.key
    volumes:
      - /data/registry:/var/lib/registry
      - /data/registry/auth:/auth
      - /data/registry/cert:/cert
    networks:
      - registry_network

networks:
  registry_network:
    driver: overlay
