---
- name: Install required Ansible collections
  hosts: localhost
  tasks:
    - name: Install community.docker collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.docker
      become: true
