---
- name: Docker and init swarm
  hosts: targets
  roles:
    - docker
    - swarm
    - nfs
    - registry
  vars:
    registry_name: "myregistry"
    registry_user: "myuser"
    registry_password: "mypassword"

- name: Docker Swarm services
  hosts: targets[0]
  roles:
    - swarm-services
  vars:
    registry_name: "myregistry"
    registry_user: "myuser"
    registry_password: "mypassword"
