---
- name: Docker and init swarm
  hosts: targets
  roles:
    - docker
    - swarm
    - nfs
    - registry
  vars_files:
    - secrets.vault

- name: Docker Swarm services
  hosts: targets[0]
  roles:
    - swarm-services
  vars_files:
    - secrets.vault

