version: '3.7'

services:
  loki:
    image: grafana/loki:2.9.1
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - loki_data:/loki
      - ./loki-config.yml:/etc/loki/loki-config.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.vcc.local`)"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.tls=true"
      - "traefik.http.routers.loki.tls.certresolver=myresolver"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
    networks:
      - web
      - traefik-net

volumes:
  loki_data:

networks:
  web:
  traefik-net:
