version: '3.7'

services:
  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail.yml:/etc/promtail/promtail.yml
    networks:
      - web
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.promtail.rule=Host(`promtail.vcc.local`)"
      - "traefik.http.routers.promtail.entrypoints=websecure"
      - "traefik.http.routers.promtail.tls=true"
      - "traefik.http.routers.promtail.tls.certresolver=myresolver"
    command:
      - -config.file=/etc/promtail/promtail.yml

networks:
  web:
  traefik-net:
