---
# tasks file for roles/docker

- name: add Docker apt repository key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: add Docker source
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
  become: yes

- name: Install Docker and docker compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: yes

- name: add vagrant user to group docker
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes
  become: true

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection
