---
- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present
  become: true

- name: Ensure Docker SDK for Python is installed
  pip:
    name: docker
    state: present
    executable: pip3
  become: true

- name: Ensure docker-compose is installed
  pip:
    name: docker-compose
    state: present
    executable: pip3
  become: true

- name: Copy docker-compose.yml to manager
  copy:
    src: files/docker-compose.yml
    dest: /home/vagrant/docker-compose.yml
  become: true

- name: Deploy Forgejo service
  community.docker.docker_compose:
    project_src: /home/vagrant
    project_name: forgejo
  become: true

